# Generated by Django 5.0 on 2025-03-10 05:37

import adverts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='advert/images/', validators=[adverts.models.validate_svg]),
        ),
    ]
