# Generated by Django 5.0 on 2025-03-10 05:39

import adverts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(upload_to='category/icons/', validators=[adverts.models.validate_svg]),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='advert/images/'),
        ),
    ]
